### ISSUE TITLE
Add import and export of data using non-proprietary formats such as CSV

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/accounts-docker#1]
The current composition of components does currently not allow import and export of data from a non-proprietary format. 

In order to test the system it needs to support automatable loading and exporting of data from a non-proprietary format. The Makefile needs and "export" and "import" target and sample data needs to be added. Preferably this would then make a batch upload over the Web API as a transaction, involving validation.

**Comment by idali0226** [comment]
This script create a initial user:


To add first user into keycloak:

docker exec usermanagementkeycloak_sso_1 keycloak/bin/add-user-keycloak.sh -u admin -p dina



On 22 May 2017, at 09:04, Markus Skyttner <notifications@github.com<mailto:notifications@github.com>> wrote:


The current composition of components does currently not allow import and export of data from a non-proprietary format.

In order to test the system it needs to support automatable loading and exporting of data from a non-proprietary format. The Makefile needs and "export" and "import" target and sample data needs to be added. Preferably this would then make a batch upload over the Web API as a transaction, involving validation.

**Comment by mikkohei13** [comment]
Users are currently loaded to Keycloak from .envapi file as described in documentation here: https://github.com/DINA-Web/documentation/wiki/Account-Management

I'll close this issue and note that we should decide and document testing procedures.
